name: Update GitHub Streak Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allow manual triggering

concurrency:
  group: push-to-main
  cancel-in-progress: false

jobs:
  update-streak-stats:
    name: Update GitHub Streak Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Streak Stats SVG
        run: |
          mkdir -p dist
          curl -s "https://github-readme-streak-stats.herokuapp.com/?user=akashverma0786&theme=tokyonight&hide_border=true&background=0D1117&ring=2F81F7&fire=2F81F7&currStreakLabel=2F81F7" \
            -o dist/streak-stats.svg

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update GitHub streak stats'
          add: 'dist/streak-stats.svg'
          push: true
